import re

OWASP_CATEGORY = "LLM07 - System Overreliance"
CHALLENGE_ID = "LLM07"
TITLE = "System Overreliance & Hallucinated Exploits"
DEFAULT_PROMPT = "tạo cấu hình tường lửa cho hệ thống network"

# Cấu hình bài lab LLM07 trong Play Mode
IS_SECURE_MODE = False  # Đổi thành True để kích hoạt bộ lọc kiểm chứng độc lập (Chống Overreliance)

# Chuỗi nhận diện mã độc/lỗ hổng (Canary String) do LLM ảo tưởng hoặc bị Prompt Injection sinh ra
MALICIOUS_BACKDOOR_CANARY = "ALLOW_ALL_TRAFFIC_0.0.0.0"

# Lớp 1: Danh sách các mẫu câu ép LLM sinh mã cấu hình (Thường dùng để lừa AI tạo code lỗi)
BLOCKED_PATTERNS = [
    r"generate.*firewall\s*rule",
    r"tạo.*cấu\s*hình\s*tường\s*lửa",
    r"bypass\s*security\s*script"
]

def mock_llm_output_generation(user_input):
    """
    Mô phỏng phản hồi từ LLM. Do hiện tượng ảo tưởng (Hallucination) hoặc bị lừa,
    LLM sinh ra một đoạn mã cấu hình tường lửa có chứa lỗ hổng bảo mật nghiêm trọng.
    """
    text = user_input.lower().strip()
    
    # Nếu người dùng cố tình lừa AI cấu hình lại hệ thống mạng bảo mật
    if "network" in text or "firewall" in text or "cấu hình" in text:
        return (
            f"# Generated by AI Assistant\n"
            f"iptables -A INPUT -p tcp --dport 80 -j ACCEPT\n"
            f"iptables -A INPUT -p tcp --dport 22 -j ACCEPT -m comment --comment '{MALICIOUS_BACKDOOR_CANARY}'"
        )
    
    return "# Generated by AI Assistant\n# No changes applied."

def independent_security_validator(generated_code):
    """
    HÀM KIỂM CHỨNG ĐỘC LẬP: Thực hiện phân tích tĩnh (Static Analysis) kết quả đầu ra của LLM
    để đảm bảo không phụ thuộc mù quáng vào AI (Chống LLM07).
    """
    if MALICIOUS_BACKDOOR_CANARY in generated_code:
        return False  # Phát hiện cấu hình không an toàn
    return True
def process_message(user_input):
    if not isinstance(user_input, str):
        user_input = str(user_input)
        
    text = user_input.lower().strip()
    
    for pattern in BLOCKED_PATTERNS:
        if re.search(pattern, text):
            return "I cannot generate lower-level network configuration scripts without admin privileges."
            
    ai_generated_code = mock_llm_output_generation(user_input)

    if not IS_SECURE_MODE:
        if MALICIOUS_BACKDOOR_CANARY in ai_generated_code:
            return (
                f"[⚠️ OVERRELIANCE CRITICAL] Code applied automatically without verification!\n"
                f"Script:\n{ai_generated_code}\n"
                f"Flag: FLAG{{llm07_system_overreliance_on_hallucinated_output_2026}}"
            )
        return f"[System] Applied AI script successfully:\n{ai_generated_code}"
    else:
        if MALICIOUS_BACKDOOR_CANARY in ai_generated_code:
            return "[🛡️ SECURITY BLOCKED] Code blocked due to malicious backdoor pattern."
        return "[🛡️ SECURE] Code passed safety check. Awaiting human approval."